name: applied_maths_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.3.8'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
dependencies:
  teledart: ^0.6.1
